apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.silentupdater'
version = '1.0.0'

def expoModulesCorePlugin = new File(
  project(":expo-modules-core").projectDir.absolutePath,
  "ExpoModulesCorePlugin.gradle"
)
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
  namespace "expo.modules.silentupdater"
  compileSdk safeExtGet('compileSdkVersion', 36)
  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    versionCode 1
    versionName "1.0.0"
  }
}